### ISSUE TITLE
User can play audio files

### ISSUE THREAD

**Issue by AsimJabariWilliams** [IDEA-LABORATORIES/RECITAL#1]
S1) Implement importing of mp3 from ios device into recital sandbox.
S2) Create audio player to play imported mp3 using AudioKit.
S3) Implement pausing.

**Comment by Daphne-CPAdmin** [comment]
NO Networking

**Comment by Daphne-CPAdmin** [comment]
Please resubmit by attaching your narrated app video in the submission notes or in the readme file. Thank you and Congratulations!
